### ISSUE TITLE
Can't access local service k8s

### ISSUE THREAD

**Issue by drazicmartin** [adaltas/ece-devops-2022-spring#5]
## Description

I did all the step of lab6 in order but i get an error `This site can’t be reached 192.168.49.2 took too long to respond.`

## To Reproduce

    minikube start

    kubectl create deployment kubernetes-bootcamp --image=gcr.io/google-samples/kubernetes-bootcamp:v1

    kubectl expose deployments/kubernetes-bootcamp --type="NodePort" --port 8080

then (if using Docker driver in Minikube) as i do:

     minikube service kubernetes-bootcamp

this jump me on webpage at [http://192.168.49.2:30508/](http://192.168.49.2:30508/) but with the error : `This site can’t be reached 192.168.49.2 took too long to respond.`

## More info 

```bash
$ kubectl get services
NAME                  TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
kubernetes            ClusterIP   10.96.0.1        <none>        443/TCP          9h
kubernetes-bootcamp   NodePort    10.111.253.239   <none>        8080:30455/TCP   2m7s
```

```bash
$ kubectl get pods
NAME                                   READY   STATUS    RESTARTS   AGE
kubernetes-bootcamp-65d5b99f84-cq8wm   1/1     Running   0          30m
```

```bash
$ minikube ip
192.168.49.2
```
   
```bash
$ minikube status
minikube
type: Control Plane
host: Running
kubelet: Running
apiserver: Running
kubeconfig: Configured
```

**Comment by sergkudinov** [comment]
Hi @drazicmartin,

Try:
- executing `curl http://localhost:8080` from inside of the container and see if it responds correctly. Use `kubectl exec ...` for that.
- If it is not working from inside, use `kubectl describe ...` and `kubectl logs ...` to see log events and understand what is wrong.
- If you are running in Docker, it might create a tunnel to your localhost `127.0.0.1`. Here is my output for Docker (the `http://127.0.0.1:63600` address is reachable, `http://192.168.49.2:30138` is not):   
```
minikube service kubernetes-bootcamp
|-----------|---------------------|-------------|---------------------------|
| NAMESPACE |        NAME         | TARGET PORT |            URL            |
|-----------|---------------------|-------------|---------------------------|
| default   | kubernetes-bootcamp |        8080 | http://192.168.49.2:30138 |
|-----------|---------------------|-------------|---------------------------|
🏃  Starting tunnel for service kubernetes-bootcamp.
|-----------|---------------------|-------------|------------------------|
| NAMESPACE |        NAME         | TARGET PORT |          URL           |
|-----------|---------------------|-------------|------------------------|
| default   | kubernetes-bootcamp |             | http://127.0.0.1:63600 |
|-----------|---------------------|-------------|------------------------|
🎉  Opening service default/kubernetes-bootcamp in default browser...
❗  Because you are using a Docker driver on darwin, the terminal needs to be open to run it.
```

If it doesn't help, probably, something is misconfigured in your VM (or Docker) networking level. Try to reach it with `ping 192.168.49.2` or connect to it. 

It is quite difficult to tell you the reason. The commands above worked correctly on my macOS on both Docker and Virtualbox environment, I've just tryied.

Tell us, if you solved this and how.

**Comment by drazicmartin** [comment]
#### The `curl http://localhost:8080` works well inside
```bash
root@kubernetes-bootcamp-65d5b99f84-cq8wm:/# curl http://localhost:8080
Hello Kubernetes bootcamp! | Running on: kubernetes-bootcamp-65d5b99f84-cq8wm | v=1
```

#### the logs are well enregistred when curl from inside but not when tring for browser 
```bash
$ kubectl logs kubernetes-bootcamp-65d5b99f84-cq8wm
Kubernetes Bootcamp App Started At: 2022-04-20T11:27:32.039Z | Running On:  kubernetes-bootcamp-65d5b99f84-cq8wm

Running On: kubernetes-bootcamp-65d5b99f84-cq8wm | Total Requests: 1 | App Uptime: 518.288 seconds | Log Time: 2022-04-20T11:36:10.327Z
Running On: kubernetes-bootcamp-65d5b99f84-cq8wm | Total Requests: 2 | App Uptime: 668.693 seconds | Log Time: 2022-04-20T11:38:40.732Z
```

#### then i try to run the tunel but it does not show me the same output as you
```bash
$ minikube service kubernetes-bootcamp
! L'exécution de "docker container inspect minikube --format={{.State.Status}}" a pris un temps inhabituellement long : 2.0217833s
* Le redémarrage du service docker peut améliorer les performances.
* Tunnel de démarrage pour le service kubernetes-bootcamp.
* Ouverture du service default/kubernetes-bootcamp dans le navigateur par défaut...
! Comme vous utilisez un pilote Docker sur windows, le terminal doit être ouvert pour l'exécuter.
```

#### I alose tried to go to every localhost show by `docker ps`
```bash
$ docker ps
CONTAINER ID   IMAGE                                 COMMAND                  CREATED        STATUS          PORTS                                                                                                                                  NAMES
91c2cd57fcf9   gcr.io/k8s-minikube/kicbase:v0.0.30   "/usr/local/bin/entr…"   19 hours ago   Up 25 minutes   127.0.0.1:58598->22/tcp, 127.0.0.1:58599->2376/tcp, 127.0.0.1:58601->5000/tcp, 127.0.0.1:58602->8443/tcp, 127.0.0.1:58600->32443/tcp   minikube
```

I only get something with this `[https://127.0.0.1:58602/](https://127.0.0.1:58602/)` depend on `http` or `https` but i error on both :
for `http` :
    Client sent an HTTP request to an HTTPS server.
for `https` : 
```json
// 20220420135817
// https://127.0.0.1:58602/

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {
    
  },
  "code": 403
}
```

**Comment by sergkudinov** [comment]
Something wrong with your Docker engine settings. Try to restart your OS or reinstall Docker.
If it doesn't help run minikube with the virtualbox driver or anyone else.

**Comment by drazicmartin** [comment]
It doesn't work with `minikube service kubernetes-bootcamp` but it works with portforwarding :
```bash
$ kubectl port-forward service/kubernetes-bootcamp 7080:8080
Forwarding from 127.0.0.1:7080 -> 8080
Forwarding from [::1]:7080 -> 8080
```
